#! /bin/sh
# /etc/init.d/sign

### BEGIN INIT INFO
# Provides:          sign
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start parmenter sign at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting sign"
    # run application you want to start
    python /home/pi/parmenter_sign/sign.py &
    ;;
  stop)
    echo "Stopping noip"
    # kill application you want to stop
    killall sign
    ;;
  *)
    echo "Usage: /etc/init.d/sign {start|stop}"
    exit 1
    ;;
esac

exit 0

